// @ts-nocheck
import { MessageMethod } from './message';
import { NotificationMethod } from './notification';
import { ModalMethod } from './modal';
import { DrawerMethod } from './drawer';

declare module 'vue' {
  export interface GlobalComponents {
    AAffix: typeof import('genedesign')['Affix'];
    AAlert: typeof import('genedesign')['Alert'];
    AAnchor: typeof import('genedesign')['Anchor'];
    AAnchorLink: typeof import('genedesign')['AnchorLink'];
    AAutoComplete: typeof import('genedesign')['AutoComplete'];
    AAvatar: typeof import('genedesign')['Avatar'];
    AAvatarGroup: typeof import('genedesign')['AvatarGroup'];
    ABackTop: typeof import('genedesign')['BackTop'];
    ABadge: typeof import('genedesign')['Badge'];
    ABreadcrumb: typeof import('genedesign')['Breadcrumb'];
    ABreadcrumbItem: typeof import('genedesign')['BreadcrumbItem'];
    AButton: typeof import('genedesign')['Button'];
    AButtonGroup: typeof import('genedesign')['ButtonGroup'];
    ACalendar: typeof import('genedesign')['Calendar'];
    ACard: typeof import('genedesign')['Card'];
    ACardMeta: typeof import('genedesign')['CardMeta'];
    ACardGrid: typeof import('genedesign')['CardGrid'];
    ACarousel: typeof import('genedesign')['Carousel'];
    ACarouselItem: typeof import('genedesign')['CarouselItem'];
    ACascader: typeof import('genedesign')['Cascader'];
    ACascaderPanel: typeof import('genedesign')['CascaderPanel'];
    ACheckbox: typeof import('genedesign')['Checkbox'];
    ACheckboxGroup: typeof import('genedesign')['CheckboxGroup'];
    ACollapse: typeof import('genedesign')['Collapse'];
    ACollapseItem: typeof import('genedesign')['CollapseItem'];
    AColorPicker: typeof import('genedesign')['ColorPicker'];
    AComment: typeof import('genedesign')['Comment'];
    AConfigProvider: typeof import('genedesign')['ConfigProvider'];
    ADatePicker: typeof import('genedesign')['DatePicker'];
    AWeekPicker: typeof import('genedesign')['WeekPicker'];
    AMonthPicker: typeof import('genedesign')['MonthPicker'];
    AYearPicker: typeof import('genedesign')['YearPicker'];
    AQuarterPicker: typeof import('genedesign')['QuarterPicker'];
    ARangePicker: typeof import('genedesign')['RangePicker'];
    ADescriptions: typeof import('genedesign')['Descriptions'];
    ADescriptionsItem: typeof import('genedesign')['DescriptionsItem'];
    ADivider: typeof import('genedesign')['Divider'];
    ADrawer: typeof import('genedesign')['Drawer'];
    ADropdown: typeof import('genedesign')['Dropdown'];
    ADoption: typeof import('genedesign')['Doption'];
    ADgroup: typeof import('genedesign')['Dgroup'];
    ADsubmenu: typeof import('genedesign')['Dsubmenu'];
    AEmpty: typeof import('genedesign')['Empty'];
    AForm: typeof import('genedesign')['Form'];
    AFormItem: typeof import('genedesign')['FormItem'];
    AGrid: typeof import('genedesign')['Grid'];
    AGridItem: typeof import('genedesign')['GridItem'];
    ACol: typeof import('genedesign')['Col'];
    ARow: typeof import('genedesign')['Row'];
    AImage: typeof import('genedesign')['Image'];
    AImagePreview: typeof import('genedesign')['ImagePreview'];
    AImagePreviewAction: typeof import('genedesign')['ImagePreviewAction'];
    AImagePreviewGroup: typeof import('genedesign')['ImagePreviewGroup'];
    AInput: typeof import('genedesign')['Input'];
    AInputGroup: typeof import('genedesign')['InputGroup'];
    AInputSearch: typeof import('genedesign')['InputSearch'];
    AInputPassword: typeof import('genedesign')['InputPassword'];
    AInputNumber: typeof import('genedesign')['InputNumber'];
    AInputTag: typeof import('genedesign')['InputTag'];
    ALayout: typeof import('genedesign')['Layout'];
    ALayoutHeader: typeof import('genedesign')['LayoutHeader'];
    ALayoutContent: typeof import('genedesign')['LayoutContent'];
    ALayoutFooter: typeof import('genedesign')['LayoutFooter'];
    ALayoutSider: typeof import('genedesign')['LayoutSider'];
    ALink: typeof import('genedesign')['Link'];
    AList: typeof import('genedesign')['List'];
    AListItem: typeof import('genedesign')['ListItem'];
    AListItemMeta: typeof import('genedesign')['ListItemMeta'];
    AMention: typeof import('genedesign')['Mention'];
    AMenu: typeof import('genedesign')['Menu'];
    AMenuItem: typeof import('genedesign')['MenuItem'];
    AMenuItemGroup: typeof import('genedesign')['MenuItemGroup'];
    ASubMenu: typeof import('genedesign')['SubMenu'];
    AModal: typeof import('genedesign')['Modal'];
    APageHeader: typeof import('genedesign')['PageHeader'];
    APagination: typeof import('genedesign')['Pagination'];
    APopconfirm: typeof import('genedesign')['Popconfirm'];
    APopover: typeof import('genedesign')['Popover'];
    AProgress: typeof import('genedesign')['Progress'];
    ARadio: typeof import('genedesign')['Radio'];
    ARadioGroup: typeof import('genedesign')['RadioGroup'];
    ARate: typeof import('genedesign')['Rate'];
    AResizeBox: typeof import('genedesign')['ResizeBox'];
    AResult: typeof import('genedesign')['Result'];
    ASelect: typeof import('genedesign')['Select'];
    AOption: typeof import('genedesign')['Option'];
    AOptgroup: typeof import('genedesign')['Optgroup'];
    ASkeleton: typeof import('genedesign')['Skeleton'];
    ASkeletonLine: typeof import('genedesign')['SkeletonLine'];
    ASkeletonShape: typeof import('genedesign')['SkeletonShape'];
    ASlider: typeof import('genedesign')['Slider'];
    ASpace: typeof import('genedesign')['Space'];
    ASpin: typeof import('genedesign')['Spin'];
    ASplit: typeof import('genedesign')['Split'];
    AStatistic: typeof import('genedesign')['Statistic'];
    ACountdown: typeof import('genedesign')['Countdown'];
    ASteps: typeof import('genedesign')['Steps'];
    AStep: typeof import('genedesign')['Step'];
    ASwitch: typeof import('genedesign')['Switch'];
    ATable: typeof import('genedesign')['Table'];
    AThead: typeof import('genedesign')['Thead'];
    ATd: typeof import('genedesign')['Td'];
    ATh: typeof import('genedesign')['Th'];
    ATr: typeof import('genedesign')['Tr'];
    ATbody: typeof import('genedesign')['Tbody'];
    ATableColumn: typeof import('genedesign')['TableColumn'];
    ATabs: typeof import('genedesign')['Tabs'];
    ATabPane: typeof import('genedesign')['TabPane'];
    ATag: typeof import('genedesign')['Tag'];
    ATextarea: typeof import('genedesign')['Textarea'];
    ATimePicker: typeof import('genedesign')['TimePicker'];
    ATimeline: typeof import('genedesign')['Timeline'];
    ATimelineItem: typeof import('genedesign')['TimelineItem'];
    ATooltip: typeof import('genedesign')['Tooltip'];
    ATransfer: typeof import('genedesign')['Transfer'];
    ATree: typeof import('genedesign')['Tree'];
    ATreeSelect: typeof import('genedesign')['TreeSelect'];
    ATrigger: typeof import('genedesign')['Trigger'];
    ATypography: typeof import('genedesign')['Typography'];
    ATypographyParagraph: typeof import('genedesign')['TypographyParagraph'];
    ATypographyTitle: typeof import('genedesign')['TypographyTitle'];
    ATypographyText: typeof import('genedesign')['TypographyText'];
    AUpload: typeof import('genedesign')['Upload'];
    AVerificationCode: typeof import('genedesign')['VerificationCode'];
    AWatermark: typeof import('genedesign')['Watermark'];
  }

  export interface ComponentCustomProperties {
    $message: MessageMethod;
    $notification: NotificationMethod;
    $modal: ModalMethod;
    $drawer: DrawerMethod;
  }
}

export {};
